// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBojr-VYLCCu_Vijaguv9RrofIv1BmH9IQ',
    appId: '1:157916756556:web:c115cfe53f8c8cc9add2e9',
    messagingSenderId: '157916756556',
    projectId: 'my-flash-chat-app-bcae0',
    authDomain: 'my-flash-chat-app-bcae0.firebaseapp.com',
    databaseURL: 'https://my-flash-chat-app-bcae0-default-rtdb.firebaseio.com',
    storageBucket: 'my-flash-chat-app-bcae0.appspot.com',
    measurementId: 'G-1S28RCW4E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTPHuOyVNKIPYAYagNoqRhgRgWDNFSQw',
    appId: '1:157916756556:android:356a3b8d635f2f67add2e9',
    messagingSenderId: '157916756556',
    projectId: 'my-flash-chat-app-bcae0',
    databaseURL: 'https://my-flash-chat-app-bcae0-default-rtdb.firebaseio.com',
    storageBucket: 'my-flash-chat-app-bcae0.appspot.com',
  );
}
